import * as React from 'react';
import Box from '@mui/material/Box';
import { DataGrid, GridToolbar } from '@mui/x-data-grid';

const columns = [
  {
    field: 'order_date',
    headerName: 'Date',
    width: 200,
    valueGetter: (value) => `${value.row.order_date}`,
  },
  {
    field: 'full_order_no',
    headerName: 'Order Number',
    width: 150,
  },
  {
    field: 'client_code',
    headerName: 'Supp. Code',
    width: 100,
  },
  {
    field: 'client_name',
    headerName: 'Supplier',
    width: 150,
  },
  {
    field: 'status_des',
    headerName: 'Order Status',
    description: 'This column has a value getter and is not sortable.',
    sortable: false,
    width: 160,
    // valueGetter: (value, row) =>
    //   `${row?.firstName || ''} ${row?.lastName || ''}`,
  },
  {
    field: 'dispatch_method_desc',
    headerName: 'Order Method',
    width: 110,
  },
  {
    field: 'source',
    headerName: 'Source',
    width: 110,
  },
  {
    field: 'originator',
    headerName: 'Originator',
    width: 110,
  },
  {
    field: 'crossyear',
    headerName: 'Cross Year',
    width: 110,
  },
];

const rows = [
  {
    id: 84974,
    year_id: 25,
    user_authorised: null,
    cancelled_on: null,
    catalogue_order: 'F',
    deliv_status: null,
    deliv_date1: null,
    deliv_date2: null,
    deliv_instr_code: '1',
    deliv_instr_text: '',
    invoice_status: null,
    latest: 'T',
    previous_version: null,
    no_prints: 0,
    order_date: '2024-01-16T17:12:42.613',
    order_no: null,
    order_prefix: 'BANK',
    order_type: 'S',
    bank_id: 51,
    user_raised: 6,
    remaining: 0,
    reminder_date: null,
    reminder_type: null,
    transfer: null,
    book_id: 2053,
    client_id: 44,
    delivery_address:
      'Green Abbey School Monkmr Road East Town Eastshire SI2 5AP',
    order_status: 'A',
    full_order_no: '#00084974 (BANK)',
    narrative: null,
    action: null,
    trans_no: null,
    being_edited: 'T',
    version_number: 1,
    user_raised_code: 'SYS',
    user_authorised_code: null,
    total_amount: 90,
    status_des: 'Not Yet Authorised',
    client_code: '00000045',
    client_name: '1st Glass',
    client_on_hold: 'F',
    client_in_use: 'T',
    client_credit_limit: 500,
    client_balance: 7200,
    client_min_order: 100,
    client_order_method: 'P',
    client_edi_carrier: null,
    client_compound_address:
      '1st Glass\r\n15 Cornfield Lane\r\nGoldington\r\nBedford',
    client_catalogue: 'F',
    focus_bar_text: '#00084974 (BANK) 1st Glass',
    transfer_code: null,
    transfer_text: '',
    last_update: null,
    source: 'FMS',
    originator: 'SYS',
    supplier_contact_name: null,
    first_output_method: null,
    order_dt_sort: '1',
    dispatch_method_desc: 'Print',
    client_eOrdering_email: null,
    dispatch_method: 'P',
  },
  {
    id: 84973,
    year_id: 25,
    user_authorised: null,
    cancelled_on: null,
    catalogue_order: 'F',
    deliv_status: null,
    deliv_date1: null,
    deliv_date2: null,
    deliv_instr_code: '1',
    deliv_instr_text: '',
    invoice_status: null,
    latest: 'T',
    previous_version: null,
    no_prints: 0,
    order_date: '2024-01-12T13:28:42.933',
    order_no: null,
    order_prefix: 'BANK',
    order_type: 'S',
    bank_id: 49,
    user_raised: 6,
    remaining: 0,
    reminder_date: null,
    reminder_type: null,
    transfer: null,
    book_id: 2053,
    client_id: 44,
    delivery_address:
      'Green Abbey School Monkmr Road East Town Eastshire SI2 5AP',
    order_status: 'A',
    full_order_no: '#00084973 (BANK)',
    narrative: null,
    action: null,
    trans_no: null,
    being_edited: 'T',
    version_number: 1,
    user_raised_code: 'SYS',
    user_authorised_code: null,
    total_amount: 100,
    status_des: 'Not Yet Authorised',
    client_code: '00000045',
    client_name: '1st Glass',
    client_on_hold: 'F',
    client_in_use: 'T',
    client_credit_limit: 500,
    client_balance: 7200,
    client_min_order: 100,
    client_order_method: 'P',
    client_edi_carrier: null,
    client_compound_address:
      '1st Glass\r\n15 Cornfield Lane\r\nGoldington\r\nBedford',
    client_catalogue: 'F',
    focus_bar_text: '#00084973 (BANK) 1st Glass',
    transfer_code: null,
    transfer_text: '',
    last_update: null,
    source: 'FMS',
    originator: 'SYS',
    supplier_contact_name: null,
    first_output_method: null,
    order_dt_sort: '1',
    dispatch_method_desc: 'Print',
    client_eOrdering_email: null,
    dispatch_method: 'P',
  },
  {
    id: 84972,
    year_id: 25,
    user_authorised: null,
    cancelled_on: null,
    catalogue_order: 'F',
    deliv_status: null,
    deliv_date1: null,
    deliv_date2: null,
    deliv_instr_code: '1',
    deliv_instr_text: 'Test',
    invoice_status: null,
    latest: 'T',
    previous_version: null,
    no_prints: 0,
    order_date: '2024-01-12T13:13:51.66',
    order_no: null,
    order_prefix: 'BANK',
    order_type: 'S',
    bank_id: 49,
    user_raised: 6,
    remaining: 0,
    reminder_date: null,
    reminder_type: null,
    transfer: null,
    book_id: 2053,
    client_id: 44,
    delivery_address:
      'Green Abbey School Monkmr Road East Town Eastshire SI2 5AP',
    order_status: 'A',
    full_order_no: '#00084972 (BANK)',
    narrative: null,
    action: null,
    trans_no: null,
    being_edited: 'T',
    version_number: 1,
    user_raised_code: 'SYS',
    user_authorised_code: null,
    total_amount: 90,
    status_des: 'Not Yet Authorised',
    client_code: '00000045',
    client_name: '1st Glass',
    client_on_hold: 'F',
    client_in_use: 'T',
    client_credit_limit: 500,
    client_balance: 7200,
    client_min_order: 100,
    client_order_method: 'P',
    client_edi_carrier: null,
    client_compound_address:
      '1st Glass\r\n15 Cornfield Lane\r\nGoldington\r\nBedford',
    client_catalogue: 'F',
    focus_bar_text: '#00084972 (BANK) 1st Glass',
    transfer_code: null,
    transfer_text: '',
    last_update: null,
    source: 'FMS',
    originator: 'SYS',
    supplier_contact_name: null,
    first_output_method: null,
    order_dt_sort: '1',
    dispatch_method_desc: 'Print',
    client_eOrdering_email: null,
    dispatch_method: 'P',
  },
];

export default function ViewTable() {
  return (
    <Box sx={{ height: 400, width: '100%' }}>
      <DataGrid
        rows={rows}
        columns={columns}
        initialState={{
          pagination: {
            paginationModel: {
              pageSize: 5,
            },
          },
        }}
        pageSizeOptions={[5]}
        checkboxSelection
        disableRowSelectionOnClick
        slots={{ toolbar: GridToolbar }}
        slotProps={{
          toolbar: {
            showQuickFilter: true,
          },
        }}
      />
    </Box>
  );
}
